name: check

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  plugins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check catalog
        run: python3 .github/workflows/check.py
